data.source.type=mongo

file.path=resources/V103_Mock.txt

mongo.uri=mongodb://10.203.43.250:27017
mongo.database=Gift-Unity
mongo.collection=scenario-topic

service.port=8081

entropy.window.size=90
